services:
  bulbasaur-website:
    container_name: bulbasaur-website
    build:
      context: .
      dockerfile: Dockerfile
    image: bulbasaur-website:latest
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
